#!/bin/sh
#
# ~/.vnc/xstartup
# cp ~/bin/xrdp/xstartup ~/.vnc/xstartup
# ln -s ~/bin/xrdp/xstartup ~/.vnc/xstartup

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

touch ~/.Xresources

startxfce4 &

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

xrdb $HOME/.Xresources
xsetroot -solid grey
# exec sh /etc/X11/xinit/xinitrc
# xfce4-terminal -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" & 

x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &

# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1

#/etc/X11/Xsession
# startxfce4 &

